name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04  # ✅ FIXED here

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 5.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/VulnerableApi/VulnerableApi.csproj

      - name: Build
        run: dotnet build ./src/VulnerableApi/VulnerableApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/VulnerableApi/VulnerableApi.csproj -c Release -o ./publish
