name: .NET CI with Security Scanning
 
on:
  push:
    branches: [ main ]
  pull_request:
 
jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
 
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_VERBOSE: true
          GITLEAKS_REDACT: true
          GITLEAKS_EXIT_CODE: 2
          GITLEAKS_REPORT_FORMAT: sarif
          GITLEAKS_REPORT_PATH: results.sarif
 
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
 
  build:
    needs: security-scan
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
 
      - name: Restore dependencies
        run: dotnet restore ./src/VulnerableApi/VulnerableApi.csproj
 
      - name: Build
        run: dotnet build ./src/VulnerableApi/VulnerableApi.csproj --configuration Release --no-restore
 
      - name: Publish
        run: dotnet publish ./src/VulnerableApi/VulnerableApi.csproj -c Release -o ./publish
 
  container-scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Build Docker image
        run: docker build -t vulnerable-api .
 
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: vulnerable-api
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
 
 